export const dashboardPreviewData = {
  activeEvents: [
    {
      id: 'star-night-2026',
      name: 'Star Night 2026',
      status: 'live',
      statusLabel: 'Live operations',
      dateLabel: '14 February 2026',
      dateTime: 'Saturday, 14 February · 7:30 PM - 10:30 PM',
      venue: 'Rooftop Observatory',
      progress: 68,
      phase: 'Final readiness',
      budget: { allocated: 5000, spent: 2750 },
      resources: { confirmed: 8, total: 10, pending: 2 },
      attendance: { expected: 60, current: 42 },
      documentation: { complete: 3, total: 5 },
      timeline: [
        { time: '5:30 PM', title: 'Venue handover', detail: 'Observatory access confirmed', state: 'complete' },
        { time: '6:45 PM', title: 'Equipment check', detail: 'PA system and projector', state: 'current' },
        { time: '7:30 PM', title: 'Doors open', detail: 'Welcome desk begins', state: 'pending' },
        { time: '8:15 PM', title: 'Sky session', detail: 'Guided telescope viewing', state: 'pending' },
      ],
      budgetItems: [{ label: 'Venue deposit', value: 1500 }, { label: 'Food and hospitality', value: 850 }, { label: 'Publicity', value: 400 }],
      resourcesList: [{ name: 'PA System', state: 'Ready' }, { name: 'Projector', state: 'Ready' }, { name: 'Lighting kit', state: 'Pending' }],
      documents: [{ name: 'Event brief', state: 'Ready' }, { name: 'Safety checklist', state: 'Ready' }, { name: 'Post-event report', state: 'Queued' }],
    },
    {
      id: 'telescope-workshop',
      name: 'Telescope Workshop',
      status: 'upcoming',
      statusLabel: 'Preparing',
      dateLabel: '28 February 2026',
      dateTime: 'Saturday, 28 February · 3:00 PM - 5:00 PM',
      venue: 'Innovation Lab',
      progress: 36,
      phase: 'Resource planning',
      budget: { allocated: 3200, spent: 900 },
      resources: { confirmed: 4, total: 7, pending: 3 },
      attendance: { expected: 35, current: 0 },
      documentation: { complete: 2, total: 5 },
      timeline: [{ time: '1:30 PM', title: 'Room setup', detail: 'Lab access and tables', state: 'pending' }, { time: '2:30 PM', title: 'Facilitator check-in', detail: 'Materials handoff', state: 'pending' }, { time: '3:00 PM', title: 'Workshop opens', detail: 'Participant welcome', state: 'pending' }],
      budgetItems: [{ label: 'Workshop materials', value: 550 }, { label: 'Print material', value: 350 }],
      resourcesList: [{ name: 'Telescope kit', state: 'Ready' }, { name: 'Soldering stations', state: 'Pending' }, { name: 'Projection screen', state: 'Pending' }],
      documents: [{ name: 'Workshop brief', state: 'Ready' }, { name: 'Facilitator notes', state: 'Ready' }, { name: 'Attendance summary', state: 'Queued' }],
    },
  ],
  timelineEvent: {
    title: 'Star Night 2026',
    date: 'Friday, 14 February · 7:30 PM',
    venue: 'Rooftop Observatory',
    status: 'upcoming',
    statusLabel: 'Upcoming',
    steps: [
      { label: 'Event plan', detail: 'Run of show is ready', state: 'complete' },
      { label: 'Budget review', detail: 'Two items need approval', state: 'current' },
      { label: 'Resources', detail: 'Allocation opens next', state: 'pending' },
      { label: 'Event day', detail: '14 February', state: 'pending' },
      { label: 'Post event', detail: 'Report and archive', state: 'pending' },
    ],
  },
  modules: [
    { id: 'plan', title: 'Plan Event', eyebrow: 'Create & organise', tone: 'brass', floatDelay: 0.2, preview: { draftEvent: 'Star Night 2026', planningPhase: 'Budget Review', nextAction: 'Approve venue booking', draftSaved: true } },
    { id: 'active', title: 'Active Event', eyebrow: 'In progress', tone: 'blue', floatDelay: 1.7, preview: { event: 'Star Night 2026', phase: 'Budget review', date: '14 Feb', pendingTasks: 3 } },
    { id: 'budget', title: 'Budget', eyebrow: 'Finance', tone: 'neutral', floatDelay: 0.8, preview: { allocated: '₹5,000', spent: '₹2,750', remaining: '₹2,250', progress: 55, nextExpense: 'Venue deposit ₹1,500', budgetHealth: 'On track' } },
    { id: 'resources', title: 'Resources', eyebrow: 'Operations', tone: 'neutral', floatDelay: 2.4, preview: { available: '12', reserved: '8', requests: '2', recentReservations: [{ name: 'PA System', status: 'confirmed' }, { name: 'Projector', status: 'confirmed' }], awaitingApproval: [{ name: 'Lighting kit', status: 'pending' }] } },
    { id: 'documentation', title: 'Documentation', eyebrow: 'Post-event', tone: 'blue', floatDelay: 1.2, preview: { pendingReports: '2', lastReport: 'Nebula Nights', recentActivity: ['Tech report submitted', 'Photo archive updated'], reviewQueue: '3 reports awaiting review', exportHistory: 'Last export: 2 days ago' } },
    { id: 'gallery', title: 'Image Gallery', eyebrow: 'Visual archive', tone: 'brass', floatDelay: 2.9, preview: { albums: [{ title: 'Star Night 2026', photos: 128, videos: 6, date: '14 Feb 2026', art: 'aurora' }, { title: 'Deep Sky Session', photos: 42, videos: 0, date: '8 Mar 2026', art: 'deep-sky' }, { title: 'Nebula Nights', photos: 73, videos: 3, date: '22 Jan 2026', art: 'nebula' }, { title: 'Telescope Workshop', photos: 31, videos: 2, date: '15 Feb 2026', art: 'telescope' }, { title: 'Galaxy Watch', photos: 58, videos: 4, date: '10 Dec 2025', art: 'galaxy' }] } },
  ],
};
